/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votingui;

/**
 *
 * @author harshit
 */
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Candidate candidateDetail;
    Voter voterDetail;
    private int isVoting;
    private int voterID;
    
    public Home() {
        isVoting = 0;
        voterID = -1;
        candidateDetail = new Candidate();
        voterDetail = new Voter();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        contentPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subTitleLabel = new javax.swing.JLabel();
        designLabel = new javax.swing.JLabel();
        leftbottomPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        userLeftPanel = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        subTitleLabel1 = new javax.swing.JLabel();
        leftbottomPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        votePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resultPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        adminLeftPanel = new javax.swing.JPanel();
        titleLabel2 = new javax.swing.JLabel();
        subTitleLabel2 = new javax.swing.JLabel();
        leftbottomPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        yesAdmin = new javax.swing.JRadioButton();
        noAdmin = new javax.swing.JRadioButton();
        yesNoPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        resultPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        logoutPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        resetVotePanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        exitPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        loginContentPanel = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        userFocusPanel = new javax.swing.JPanel();
        passwordFocusPanel = new javax.swing.JPanel();
        resetPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        submitPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adminRadio = new javax.swing.JRadioButton();
        inactiveRight = new javax.swing.JPanel();
        exitPanel1 = new javax.swing.JPanel();
        exitInactiveLabel = new javax.swing.JLabel();
        resultRight = new javax.swing.JPanel();
        exitPanel2 = new javax.swing.JPanel();
        exitInactiveLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cand1vote = new javax.swing.JLabel();
        cand2vote = new javax.swing.JLabel();
        cand3vote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Voting System");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);
        setResizable(false);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(200, 0, 255));

        titleLabel.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Welcome to Clustered Vote");

        subTitleLabel.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        subTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        subTitleLabel.setText("The Home of democracy at Cluster Innovation Centre");

        designLabel.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        designLabel.setForeground(new java.awt.Color(255, 255, 255));
        designLabel.setText("<html>\nGuide for this application:\n<ul>\n<li>Admin Panel\n<ul>\n<li>Admin can start or stop the voting\n<li>Admin can view the results at any point of time, <br>\nirrespective of the status of voting.\n</ul>\n<li>User Panel\n<ul>\n<li>When voting is live, user can vote for their favourite candidate <br>\nbut cannot view resuts.\n<li>When voting is NOT live, user cannot vote but can view the resuts.\n</u>\n</ul>\n</html>");

        leftbottomPanel.setBackground(new java.awt.Color(137, 17, 156));
        leftbottomPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harshit Joshi");

        javax.swing.GroupLayout leftbottomPanelLayout = new javax.swing.GroupLayout(leftbottomPanel);
        leftbottomPanel.setLayout(leftbottomPanelLayout);
        leftbottomPanelLayout.setHorizontalGroup(
            leftbottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        leftbottomPanelLayout.setVerticalGroup(
            leftbottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftbottomPanelLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftbottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subTitleLabel)
                            .addComponent(titleLabel)
                            .addComponent(designLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 96, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(subTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(designLabel)
                .addGap(61, 61, 61)
                .addComponent(leftbottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contentPanel.add(homePanel, "card2");

        userLeftPanel.setBackground(new java.awt.Color(250, 250, 250));

        titleLabel1.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        titleLabel1.setText("User Login");

        subTitleLabel1.setText("Vote for your favourite candidate");

        leftbottomPanel1.setBackground(new java.awt.Color(137, 17, 156));
        leftbottomPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harshit Joshi");

        javax.swing.GroupLayout leftbottomPanel1Layout = new javax.swing.GroupLayout(leftbottomPanel1);
        leftbottomPanel1.setLayout(leftbottomPanel1Layout);
        leftbottomPanel1Layout.setHorizontalGroup(
            leftbottomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftbottomPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(79, 79, 79))
        );
        leftbottomPanel1Layout.setVerticalGroup(
            leftbottomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftbottomPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Prakhar Aggarwal");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Hardik Kapoor");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Mayank Malik");

        votePanel.setBackground(new java.awt.Color(122, 1, 122));
        votePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                votePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                votePanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                votePanelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VOTE");

        javax.swing.GroupLayout votePanelLayout = new javax.swing.GroupLayout(votePanel);
        votePanel.setLayout(votePanelLayout);
        votePanelLayout.setHorizontalGroup(
            votePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, votePanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );
        votePanelLayout.setVerticalGroup(
            votePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        resultPanel.setBackground(new java.awt.Color(122, 1, 122));
        resultPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resultPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resultPanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultPanelMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RESULT");

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        logoutPanel.setBackground(new java.awt.Color(122, 1, 122));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LOGOUT");

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingui/prakhar.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 0, 173), 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingui/mayank.jpg"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 0, 173), 4));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingui/hard.jpg"))); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 0, 173), 4));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel18.setText("<html>\nCurrent CR\n<br>No one Likes him\n</html>");

        jLabel19.setText("<html>\nChill person\n<br>\nLow Attendance\n</html>");

        jLabel20.setText("<html>\nHardworking person\n<br>\nReally Sweet\n</html>");

        javax.swing.GroupLayout userLeftPanelLayout = new javax.swing.GroupLayout(userLeftPanel);
        userLeftPanel.setLayout(userLeftPanelLayout);
        userLeftPanelLayout.setHorizontalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLeftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLeftPanelLayout.createSequentialGroup()
                        .addComponent(subTitleLabel1)
                        .addContainerGap(419, Short.MAX_VALUE))
                    .addGroup(userLeftPanelLayout.createSequentialGroup()
                        .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel1)
                            .addGroup(userLeftPanelLayout.createSequentialGroup()
                                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userLeftPanelLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(userLeftPanelLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton2))))
                                .addGap(35, 35, 35)
                                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(userLeftPanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(userLeftPanelLayout.createSequentialGroup()
                                .addComponent(votePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userLeftPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addComponent(leftbottomPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        userLeftPanelLayout.setVerticalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(titleLabel1)
                .addGap(18, 18, 18)
                .addComponent(subTitleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(votePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leftbottomPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userLeftPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        contentPanel.add(userLeftPanel, "card2");

        adminLeftPanel.setBackground(new java.awt.Color(250, 250, 250));

        titleLabel2.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        titleLabel2.setText("Admin Login");

        subTitleLabel2.setText("Is the Voting active?");

        leftbottomPanel2.setBackground(new java.awt.Color(137, 17, 156));
        leftbottomPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Harshit Joshi");

        javax.swing.GroupLayout leftbottomPanel2Layout = new javax.swing.GroupLayout(leftbottomPanel2);
        leftbottomPanel2.setLayout(leftbottomPanel2Layout);
        leftbottomPanel2Layout.setHorizontalGroup(
            leftbottomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftbottomPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftbottomPanel2Layout.setVerticalGroup(
            leftbottomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftbottomPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        buttonGroup1.add(yesAdmin);
        yesAdmin.setText("Yes");

        buttonGroup1.add(noAdmin);
        noAdmin.setText("No");

        yesNoPanel.setBackground(new java.awt.Color(122, 1, 122));
        yesNoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                yesNoPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                yesNoPanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesNoPanelMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SUBMIT");

        javax.swing.GroupLayout yesNoPanelLayout = new javax.swing.GroupLayout(yesNoPanel);
        yesNoPanel.setLayout(yesNoPanelLayout);
        yesNoPanelLayout.setHorizontalGroup(
            yesNoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yesNoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
        yesNoPanelLayout.setVerticalGroup(
            yesNoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        resultPanel1.setBackground(new java.awt.Color(122, 1, 122));
        resultPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resultPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resultPanel1MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultPanel1MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("RESULT");

        javax.swing.GroupLayout resultPanel1Layout = new javax.swing.GroupLayout(resultPanel1);
        resultPanel1.setLayout(resultPanel1Layout);
        resultPanel1Layout.setHorizontalGroup(
            resultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        resultPanel1Layout.setVerticalGroup(
            resultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        logoutPanel1.setBackground(new java.awt.Color(122, 1, 122));
        logoutPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanel1MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("DejaVu Sans Light", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LOGOUT");

        javax.swing.GroupLayout logoutPanel1Layout = new javax.swing.GroupLayout(logoutPanel1);
        logoutPanel1.setLayout(logoutPanel1Layout);
        logoutPanel1Layout.setHorizontalGroup(
            logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoutPanel1Layout.setVerticalGroup(
            logoutPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        resetVotePanel.setBackground(new java.awt.Color(122, 1, 122));
        resetVotePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetVotePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resetVotePanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetVotePanelMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("RESET");

        javax.swing.GroupLayout resetVotePanelLayout = new javax.swing.GroupLayout(resetVotePanel);
        resetVotePanel.setLayout(resetVotePanelLayout);
        resetVotePanelLayout.setHorizontalGroup(
            resetVotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetVotePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel21)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        resetVotePanelLayout.setVerticalGroup(
            resetVotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout adminLeftPanelLayout = new javax.swing.GroupLayout(adminLeftPanel);
        adminLeftPanel.setLayout(adminLeftPanelLayout);
        adminLeftPanelLayout.setHorizontalGroup(
            adminLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLeftPanelLayout.createSequentialGroup()
                .addComponent(leftbottomPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 319, Short.MAX_VALUE))
            .addGroup(adminLeftPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(adminLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLeftPanelLayout.createSequentialGroup()
                        .addGroup(adminLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noAdmin)
                            .addComponent(yesAdmin)
                            .addComponent(subTitleLabel2)
                            .addGroup(adminLeftPanelLayout.createSequentialGroup()
                                .addComponent(yesNoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resultPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(resetVotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(250, Short.MAX_VALUE))
                    .addGroup(adminLeftPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminLeftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminLeftPanelLayout.setVerticalGroup(
            adminLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLeftPanelLayout.createSequentialGroup()
                .addComponent(logoutPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(titleLabel2)
                .addGap(18, 18, 18)
                .addComponent(subTitleLabel2)
                .addGap(18, 18, 18)
                .addComponent(yesAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noAdmin)
                .addGap(18, 18, 18)
                .addGroup(adminLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLeftPanelLayout.createSequentialGroup()
                        .addGroup(adminLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yesNoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetVotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addComponent(leftbottomPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminLeftPanelLayout.createSequentialGroup()
                        .addComponent(resultPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        contentPanel.add(adminLeftPanel, "card2");

        rightPanel.setBackground(new java.awt.Color(231, 200, 235));
        rightPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(231, 200, 235));

        exitPanel.setBackground(new java.awt.Color(137, 17, 156));
        exitPanel.setForeground(new java.awt.Color(255, 255, 255));
        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit(evt);
            }
        });

        exitLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setText("EXIT");

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitLabel)
                .addContainerGap())
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        loginContentPanel.setBackground(new java.awt.Color(231, 200, 235));

        usernameField.setBackground(new java.awt.Color(255, 255, 255));
        usernameField.setFont(new java.awt.Font("DejaVu Sans Light", 0, 18)); // NOI18N
        usernameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameField.setText("Username");
        usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 2));
        usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFieldFocusLost(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        passwordField.setText("Password");
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 2));
        passwordField.setName(""); // NOI18N
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        userFocusPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout userFocusPanelLayout = new javax.swing.GroupLayout(userFocusPanel);
        userFocusPanel.setLayout(userFocusPanelLayout);
        userFocusPanelLayout.setHorizontalGroup(
            userFocusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        userFocusPanelLayout.setVerticalGroup(
            userFocusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        passwordFocusPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout passwordFocusPanelLayout = new javax.swing.GroupLayout(passwordFocusPanel);
        passwordFocusPanel.setLayout(passwordFocusPanelLayout);
        passwordFocusPanelLayout.setHorizontalGroup(
            passwordFocusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        passwordFocusPanelLayout.setVerticalGroup(
            passwordFocusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        resetPanel.setBackground(new java.awt.Color(104, 1, 123));
        resetPanel.setForeground(new java.awt.Color(254, 254, 254));
        resetPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resetPanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPanelMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESET");

        javax.swing.GroupLayout resetPanelLayout = new javax.swing.GroupLayout(resetPanel);
        resetPanel.setLayout(resetPanelLayout);
        resetPanelLayout.setHorizontalGroup(
            resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        resetPanelLayout.setVerticalGroup(
            resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        submitPanel.setBackground(new java.awt.Color(104, 1, 123));
        submitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                submitPanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitPanelMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SUBMIT");

        javax.swing.GroupLayout submitPanelLayout = new javax.swing.GroupLayout(submitPanel);
        submitPanel.setLayout(submitPanelLayout);
        submitPanelLayout.setHorizontalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        submitPanelLayout.setVerticalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        adminRadio.setText("Admin Login");

        javax.swing.GroupLayout loginContentPanelLayout = new javax.swing.GroupLayout(loginContentPanel);
        loginContentPanel.setLayout(loginContentPanelLayout);
        loginContentPanelLayout.setHorizontalGroup(
            loginContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(loginContentPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(loginContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginContentPanelLayout.createSequentialGroup()
                        .addComponent(resetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(submitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginContentPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(loginContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userFocusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordFocusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(loginContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField)
                            .addComponent(usernameField))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginContentPanelLayout.setVerticalGroup(
            loginContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContentPanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(loginContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(userFocusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(loginContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(passwordFocusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(adminRadio)
                .addGap(18, 18, 18)
                .addGroup(loginContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(loginContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        rightPanel.add(loginPanel, "card2");

        inactiveRight.setBackground(new java.awt.Color(231, 200, 235));

        exitPanel1.setBackground(new java.awt.Color(137, 17, 156));
        exitPanel1.setForeground(new java.awt.Color(255, 255, 255));
        exitPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPanel1exit(evt);
            }
        });

        exitInactiveLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        exitInactiveLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitInactiveLabel.setText("EXIT");

        javax.swing.GroupLayout exitPanel1Layout = new javax.swing.GroupLayout(exitPanel1);
        exitPanel1.setLayout(exitPanel1Layout);
        exitPanel1Layout.setHorizontalGroup(
            exitPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitInactiveLabel)
                .addContainerGap())
        );
        exitPanel1Layout.setVerticalGroup(
            exitPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanel1Layout.createSequentialGroup()
                .addComponent(exitInactiveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout inactiveRightLayout = new javax.swing.GroupLayout(inactiveRight);
        inactiveRight.setLayout(inactiveRightLayout);
        inactiveRightLayout.setHorizontalGroup(
            inactiveRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inactiveRightLayout.createSequentialGroup()
                .addGap(0, 247, Short.MAX_VALUE)
                .addComponent(exitPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        inactiveRightLayout.setVerticalGroup(
            inactiveRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inactiveRightLayout.createSequentialGroup()
                .addComponent(exitPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 501, Short.MAX_VALUE))
        );

        rightPanel.add(inactiveRight, "card2");

        resultRight.setBackground(new java.awt.Color(231, 200, 235));

        exitPanel2.setBackground(new java.awt.Color(137, 17, 156));
        exitPanel2.setForeground(new java.awt.Color(255, 255, 255));
        exitPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPanel2exit(evt);
            }
        });

        exitInactiveLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        exitInactiveLabel1.setForeground(new java.awt.Color(255, 255, 255));
        exitInactiveLabel1.setText("EXIT");

        javax.swing.GroupLayout exitPanel2Layout = new javax.swing.GroupLayout(exitPanel2);
        exitPanel2.setLayout(exitPanel2Layout);
        exitPanel2Layout.setHorizontalGroup(
            exitPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitInactiveLabel1)
                .addContainerGap())
        );
        exitPanel2Layout.setVerticalGroup(
            exitPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanel2Layout.createSequentialGroup()
                .addComponent(exitInactiveLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel1.setBackground(new java.awt.Color(246, 222, 254));

        jLabel9.setText("Prakhar Aggarwal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(126, 17, 132));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mayank Malik");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(246, 222, 254));

        jLabel11.setText("Hardik Kapoor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cand1vote.setText("0");

        cand2vote.setText("0");

        cand3vote.setText("0");

        javax.swing.GroupLayout resultRightLayout = new javax.swing.GroupLayout(resultRight);
        resultRight.setLayout(resultRightLayout);
        resultRightLayout.setHorizontalGroup(
            resultRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultRightLayout.createSequentialGroup()
                .addGap(0, 247, Short.MAX_VALUE)
                .addComponent(exitPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(resultRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultRightLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cand1vote))
                    .addGroup(resultRightLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cand2vote))
                    .addGroup(resultRightLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cand3vote)))
                .addContainerGap())
        );
        resultRightLayout.setVerticalGroup(
            resultRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultRightLayout.createSequentialGroup()
                .addComponent(exitPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(resultRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand1vote))
                .addGap(18, 18, 18)
                .addGroup(resultRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand2vote))
                .addGap(18, 18, 18)
                .addGroup(resultRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cand3vote))
                .addGap(0, 335, Short.MAX_VALUE))
        );

        rightPanel.add(resultRight, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 304, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 655, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exit

    private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
        // TODO add your handling code here:
        userFocusPanel.setBackground(new java.awt.Color(122, 26, 122));
    }//GEN-LAST:event_usernameFieldFocusGained

    private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
        // TODO add your handling code here:
        userFocusPanel.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_usernameFieldFocusLost

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        // TODO add your handling code here:
        passwordFocusPanel.setBackground(new java.awt.Color(122, 26, 122));
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        // TODO add your handling code here:
        passwordFocusPanel.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_passwordFieldFocusLost

    private void resetPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPanelMouseClicked
        // TODO add your handling code here:
        usernameField.setText("Username");
        passwordField.setText("Password");
    }//GEN-LAST:event_resetPanelMouseClicked

    private void submitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitPanelMouseClicked
        // TODO add your handling code here:
        String usernameEntered = usernameField.getText();
        String passwordEntered= passwordField.getText();
        System.out.println(usernameEntered);
        System.out.println(passwordEntered);
        if (adminRadio.isSelected()) {
            if (usernameEntered.equals("admin") && passwordEntered.equals("admin")) {
                contentPanel.removeAll();
                contentPanel.repaint();
                contentPanel.revalidate();
        
                contentPanel.add(adminLeftPanel);
                contentPanel.repaint();
                contentPanel.revalidate();
            
                rightPanel.removeAll();
                rightPanel.repaint();
                rightPanel.revalidate();
            
                rightPanel.add(inactiveRight);
                rightPanel.repaint();
                rightPanel.revalidate();
            
            }
            else {
                JOptionPane.showMessageDialog(this, "Invalid Username or Password!", "Login error", JOptionPane.ERROR_MESSAGE);
            }
        }   
        else {
            for (int i=0; i<44; ++i){
                if (usernameEntered.equals(voterDetail.getVoterUser(i)) && passwordEntered.equals(voterDetail.getVoterPass(i))) {
                    contentPanel.removeAll();
                    contentPanel.repaint();
                    contentPanel.revalidate();

                    contentPanel.add(userLeftPanel);
                    contentPanel.repaint();
                    contentPanel.revalidate();

                    rightPanel.removeAll();
                    rightPanel.repaint();
                    rightPanel.revalidate();

                    rightPanel.add(inactiveRight);
                    rightPanel.repaint();
                    rightPanel.revalidate();

                    voterID = i;
                    break;
                }
            }
            if (voterID == -1){
                JOptionPane.showMessageDialog(this, "Invalid Username or Password!", "Login error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
                
    }//GEN-LAST:event_submitPanelMouseClicked

    private void resetPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPanelMousePressed
        // TODO add your handling code here:
        resetPanel.setBackground(new java.awt.Color(40,0,48));
    }//GEN-LAST:event_resetPanelMousePressed

    private void resetPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPanelMouseReleased
        // TODO add your handling code here:
        resetPanel.setBackground(new java.awt.Color(104,1,123));
    }//GEN-LAST:event_resetPanelMouseReleased

    private void submitPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitPanelMousePressed
        // TODO add your handling code here:
        submitPanel.setBackground(new java.awt.Color(40,0,48));
    }//GEN-LAST:event_submitPanelMousePressed

    private void submitPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitPanelMouseReleased
        // TODO add your handling code here:
        submitPanel.setBackground(new java.awt.Color(104,1,123));
    }//GEN-LAST:event_submitPanelMouseReleased

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(homePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
        
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
            
        rightPanel.add(loginPanel);
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void exitPanel1exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanel1exit
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitPanel1exit

    private void votePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_votePanelMouseClicked
        // TODO add your handling code here:
        
        if (isVoting == 1) {
            if (voterDetail.getvoter(voterID) == 0) {
                int i=0;
                if (jRadioButton1.isSelected()){
                    candidateDetail.cand1();
                    cand1vote.setText(Integer.toString(candidateDetail.getcan1()));
                    System.out.print(candidateDetail.getcan1());
                    System.out.print(++i);
                }
                else if (jRadioButton2.isSelected()){
                    candidateDetail.cand2();
                    cand2vote.setText(Integer.toString(candidateDetail.getcan2()));
                    System.out.print(candidateDetail.getcan2());
                }
                else if (jRadioButton3.isSelected()){
                    candidateDetail.cand3();
                    cand3vote.setText(Integer.toString(candidateDetail.getcan3()));
                    System.out.print(candidateDetail.getcan3());
                }
                else {
                    JOptionPane.showMessageDialog(this, "Please select a candidate!", "Voting error", JOptionPane.ERROR_MESSAGE);
                }
                buttonGroup1.clearSelection();
                voterDetail.voterVoted(voterID);
                JOptionPane.showMessageDialog(this, "Thankyou for voting", "Thanks", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "You have already voted!", "Voting error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
                JOptionPane.showMessageDialog(this, "The voting is NOT live right now!", "Voting error", JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_votePanelMouseClicked

    private void exitPanel2exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanel2exit
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitPanel2exit

    private void resultPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanelMouseClicked
        // TODO add your handling code here:
        if (isVoting == 0) {
            rightPanel.removeAll();
            rightPanel.repaint();
            rightPanel.revalidate();
            
            rightPanel.add(resultRight);
            rightPanel.repaint();
            rightPanel.revalidate();
        }
        else {
                JOptionPane.showMessageDialog(this, "The voting is live right now!", "Result", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_resultPanelMouseClicked

    private void votePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_votePanelMousePressed
        // TODO add your handling code here:
        votePanel.setBackground(new java.awt.Color(40,0,48));
    }//GEN-LAST:event_votePanelMousePressed

    private void votePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_votePanelMouseReleased
        // TODO add your handling code here:
        votePanel.setBackground(new java.awt.Color(122,1,122));
    }//GEN-LAST:event_votePanelMouseReleased

    private void yesNoPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesNoPanelMousePressed
        // TODO add your handling code here:
        yesNoPanel.setBackground(new java.awt.Color(40,0,48));
    }//GEN-LAST:event_yesNoPanelMousePressed

    private void yesNoPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesNoPanelMouseReleased
        // TODO add your handling code here:
        yesNoPanel.setBackground(new java.awt.Color(122,1,122));
    }//GEN-LAST:event_yesNoPanelMouseReleased

    private void yesNoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesNoPanelMouseClicked
        // TODO add your handling code here:
        if (yesAdmin.isSelected()) {
            isVoting = 1;
        }
        if (noAdmin.isSelected()) {
            isVoting = 0;
        }
    }//GEN-LAST:event_yesNoPanelMouseClicked

    private void resultPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanel1MouseClicked
        // TODO add your handling code here:
        
            rightPanel.removeAll();
            rightPanel.repaint();
            rightPanel.revalidate();
            
            rightPanel.add(resultRight);
            rightPanel.repaint();
            rightPanel.revalidate();
       
    }//GEN-LAST:event_resultPanel1MouseClicked

    private void logoutPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanel1MouseClicked
        // TODO add your handling code here:
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(homePanel);
        contentPanel.repaint();
        contentPanel.revalidate();
        
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
            
        rightPanel.add(loginPanel);
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_logoutPanel1MouseClicked

    private void resultPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanel1MousePressed
        // TODO add your handling code here:
        resultPanel1.setBackground(new java.awt.Color(40,0,48));
    }//GEN-LAST:event_resultPanel1MousePressed

    private void resultPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanel1MouseReleased
        // TODO add your handling code here:
        resultPanel1.setBackground(new java.awt.Color(122,1,122));
    }//GEN-LAST:event_resultPanel1MouseReleased

    private void resetVotePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetVotePanelMousePressed
        // TODO add your handling code here:
        resetVotePanel.setBackground(new java.awt.Color(40,0,48));
    }//GEN-LAST:event_resetVotePanelMousePressed

    private void resetVotePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetVotePanelMouseReleased
        // TODO add your handling code here:
        resetVotePanel.setBackground(new java.awt.Color(122,1,122));
    }//GEN-LAST:event_resetVotePanelMouseReleased

    private void resetVotePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetVotePanelMouseClicked
        // TODO add your handling code here:
        candidateDetail.cand1Reset();
        cand1vote.setText(Integer.toString(0));
        candidateDetail.cand2Reset();
        cand2vote.setText(Integer.toString(0));
        candidateDetail.cand3Reset();
        cand2vote.setText(Integer.toString(0));
        
        voterDetail.voterReset();
        
        System.out.print(candidateDetail.getcan1());
    }//GEN-LAST:event_resetVotePanelMouseClicked

    private void resultPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanelMousePressed
        // TODO add your handling code here:
        resultPanel.setBackground(new java.awt.Color(40,0,48));
    }//GEN-LAST:event_resultPanelMousePressed

    private void resultPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanelMouseReleased
        // TODO add your handling code here:
        resultPanel.setBackground(new java.awt.Color(122,1,122));
    }//GEN-LAST:event_resultPanelMouseReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminLeftPanel;
    private javax.swing.JRadioButton adminRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cand1vote;
    private javax.swing.JLabel cand2vote;
    private javax.swing.JLabel cand3vote;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel designLabel;
    private javax.swing.JLabel exitInactiveLabel;
    private javax.swing.JLabel exitInactiveLabel1;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JPanel exitPanel1;
    private javax.swing.JPanel exitPanel2;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel inactiveRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPanel leftbottomPanel;
    private javax.swing.JPanel leftbottomPanel1;
    private javax.swing.JPanel leftbottomPanel2;
    private javax.swing.JPanel loginContentPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel logoutPanel1;
    private javax.swing.JRadioButton noAdmin;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel passwordFocusPanel;
    private javax.swing.JPanel resetPanel;
    private javax.swing.JPanel resetVotePanel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JPanel resultPanel1;
    private javax.swing.JPanel resultRight;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel subTitleLabel;
    private javax.swing.JLabel subTitleLabel1;
    private javax.swing.JLabel subTitleLabel2;
    private javax.swing.JPanel submitPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JPanel userFocusPanel;
    private javax.swing.JPanel userLeftPanel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JPanel votePanel;
    private javax.swing.JRadioButton yesAdmin;
    private javax.swing.JPanel yesNoPanel;
    // End of variables declaration//GEN-END:variables
}
